---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/transactions":
    get:
      summary: list transactions
      parameters:
      - name: query
        in: query
        description: Search through transactions
        required: false
      responses:
        '200':
          description: successful
    post:
      summary: create transaction
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                deposit:
                  type: number
                currency:
                  type: string
                withdrawal:
                  type: number
                amount:
                  type: number
              required:
              - user_id
              - deposit
              - currency
              - withdrawal
              - amount
  "/api/v1/transactions/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show transaction
      responses:
        '200':
          description: successful
    patch:
      summary: update transaction
      responses:
        '200':
          description: successful
    put:
      summary: update transaction
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                deposit:
                  type: number
                currency:
                  type: string
                withdrawal:
                  type: number
                amount:
                  type: number
              required:
              - user_id
              - deposit
              - currency
              - withdrawal
              - number
    delete:
      summary: delete transaction
      responses:
        '200':
          description: successful
servers:
- url: http://127.0.0.1:3000
  description: Development environment
- url: https://quikk.onrender.com
  description: Production environment
